baseURL = 'https://www.menzel.it/'
languageCode = 'en-us'
title = 'The State of the Microsoft 365 Nation'

theme = "hugo-theme-stack"
paginate = 5
disqusShortname = "hugo-theme-stack"
DefaultContentLanguage = "en"
hasCJKLanguage = false
enableRobotsTXT = true

[outputs]
  home = ['html', 'rss']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[languages]
[languages.en]
languageName = "English"
title = "The State of the Microsoft 365 Nation"
weight = 1

[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[permalinks]
page = "/:slug/"

[params.shareButtons]
  networks = [ "linkedin", "xing", "twitter", "email", "reddit" ]
  size = "small"
  icon = "solid"
  buttonMargin = "0.2em"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = false

  [params.footer]
  since = 2_020

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  emoji = ""
  subtitle = "Navigating the Digital Landscape"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/Me-NinjaCat.jpg"

  [params.article]
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = false
  provider = "disqus"

    [params.comments.disqusjs]

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]

    [params.comments.vssue]
    autoCreateIssue = false

    [params.comments.waline]
    emoji = [ "https://unpkg.com/@waline/emojis@1.0.1/weibo" ]
    requiredMeta = [ "name", "email", "url" ]

      [params.comments.waline.locale]
      admin = "Admin"

    [params.comments.twikoo]

    [params.comments.cactus]
    defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
    serverName = "cactus.chat"
    siteName = ""

    [params.comments.giscus]
    reactionsEnabled = 1
    emitMetadata = 0

    [params.comments.gitalk]

    [params.comments.cusdis]

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

  [params.widgets.homepage.params]
  limit = 5

[[params.widgets.homepage]]
type = "categories"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.page]]
type = "toc"

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
main = [ ]

  [[menu.social]]
  identifier = "rss"
  name = "RSS"
  url = "/index.xml"

    [menu.social.params]
    icon = "brand-rss"

  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/ollimenzel"

    [menu.social.params]
    icon = "brand-github"

  [[menu.social]]
  identifier = "twitter"
  name = "Twitter"
  url = "https://twitter.com/ollimenzel"

    [menu.social.params]
    icon = "brand-twitter"

  [[menu.social]]
  identifier = "linkedin"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/olivermenzel/"

    [menu.social.params]
    icon = "brand-linkedin"

  [[menu.social]]
  identifier = "Mastodon"
  name = "Mastodon"
  url = "https://techhub.social/@ollimenzel"

    [menu.social.params]
    icon = "brand-mastodon"

  [[menu.social]]
  identifier = "Bluesky"
  name = "Bluesky"
  url = "https://bsky.app/profile/menzel.it"

    [menu.social.params]
    icon = "brand-bluesky"

  [[menu.social]]
  identifier = "Threads"
  name = "Threads"
  url = "https://www.threads.net/@ollim365"

    [menu.social.params]
    icon = "brand-threads"


[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.renderer]
unsafe = false

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
